//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptorDeployment) DeepCopyInto(out *CaptorDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptorDeployment.
func (in *CaptorDeployment) DeepCopy() *CaptorDeployment {
	if in == nil {
		return nil
	}
	out := new(CaptorDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeAnnotation) DeepCopyInto(out *ChangeAnnotation) {
	*out = *in
	if in.Traps != nil {
		in, out := &in.Traps, &out.Traps
		*out = make([]TrapAnnotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeAnnotation.
func (in *ChangeAnnotation) DeepCopy() *ChangeAnnotation {
	if in == nil {
		return nil
	}
	out := new(ChangeAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeceptionPolicy) DeepCopyInto(out *DeceptionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeceptionPolicy.
func (in *DeceptionPolicy) DeepCopy() *DeceptionPolicy {
	if in == nil {
		return nil
	}
	out := new(DeceptionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeceptionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeceptionPolicyCondition) DeepCopyInto(out *DeceptionPolicyCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeceptionPolicyCondition.
func (in *DeceptionPolicyCondition) DeepCopy() *DeceptionPolicyCondition {
	if in == nil {
		return nil
	}
	out := new(DeceptionPolicyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeceptionPolicyList) DeepCopyInto(out *DeceptionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeceptionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeceptionPolicyList.
func (in *DeceptionPolicyList) DeepCopy() *DeceptionPolicyList {
	if in == nil {
		return nil
	}
	out := new(DeceptionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeceptionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeceptionPolicySpec) DeepCopyInto(out *DeceptionPolicySpec) {
	*out = *in
	if in.Traps != nil {
		in, out := &in.Traps, &out.Traps
		*out = make([]Trap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StrictValidation != nil {
		in, out := &in.StrictValidation, &out.StrictValidation
		*out = new(bool)
		**out = **in
	}
	if in.MutateExisting != nil {
		in, out := &in.MutateExisting, &out.MutateExisting
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeceptionPolicySpec.
func (in *DeceptionPolicySpec) DeepCopy() *DeceptionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DeceptionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeceptionPolicyStatus) DeepCopyInto(out *DeceptionPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DeceptionPolicyCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeceptionPolicyStatus.
func (in *DeceptionPolicyStatus) DeepCopy() *DeceptionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DeceptionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoyDeployment) DeepCopyInto(out *DecoyDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoyDeployment.
func (in *DecoyDeployment) DeepCopy() *DecoyDeployment {
	if in == nil {
		return nil
	}
	out := new(DecoyDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemHoneytoken) DeepCopyInto(out *FilesystemHoneytoken) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemHoneytoken.
func (in *FilesystemHoneytoken) DeepCopy() *FilesystemHoneytoken {
	if in == nil {
		return nil
	}
	out := new(FilesystemHoneytoken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemHoneytokenAnnotation) DeepCopyInto(out *FilesystemHoneytokenAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemHoneytokenAnnotation.
func (in *FilesystemHoneytokenAnnotation) DeepCopy() *FilesystemHoneytokenAnnotation {
	if in == nil {
		return nil
	}
	out := new(FilesystemHoneytokenAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpEndpoint) DeepCopyInto(out *HttpEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpEndpoint.
func (in *HttpEndpoint) DeepCopy() *HttpEndpoint {
	if in == nil {
		return nil
	}
	out := new(HttpEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpEndpointAnnotation) DeepCopyInto(out *HttpEndpointAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpEndpointAnnotation.
func (in *HttpEndpointAnnotation) DeepCopy() *HttpEndpointAnnotation {
	if in == nil {
		return nil
	}
	out := new(HttpEndpointAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpPayload) DeepCopyInto(out *HttpPayload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpPayload.
func (in *HttpPayload) DeepCopy() *HttpPayload {
	if in == nil {
		return nil
	}
	out := new(HttpPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpPayloadAnnotation) DeepCopyInto(out *HttpPayloadAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpPayloadAnnotation.
func (in *HttpPayloadAnnotation) DeepCopy() *HttpPayloadAnnotation {
	if in == nil {
		return nil
	}
	out := new(HttpPayloadAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchResources) DeepCopyInto(out *MatchResources) {
	*out = *in
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = make([]ResourceFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchResources.
func (in *MatchResources) DeepCopy() *MatchResources {
	if in == nil {
		return nil
	}
	out := new(MatchResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceDescription) DeepCopyInto(out *ResourceDescription) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceDescription.
func (in *ResourceDescription) DeepCopy() *ResourceDescription {
	if in == nil {
		return nil
	}
	out := new(ResourceDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceFilter) DeepCopyInto(out *ResourceFilter) {
	*out = *in
	in.ResourceDescription.DeepCopyInto(&out.ResourceDescription)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceFilter.
func (in *ResourceFilter) DeepCopy() *ResourceFilter {
	if in == nil {
		return nil
	}
	out := new(ResourceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trap) DeepCopyInto(out *Trap) {
	*out = *in
	out.FilesystemHoneytoken = in.FilesystemHoneytoken
	out.HttpEndpoint = in.HttpEndpoint
	out.HttpPayload = in.HttpPayload
	out.DecoyDeployment = in.DecoyDeployment
	out.CaptorDeployment = in.CaptorDeployment
	in.MatchResources.DeepCopyInto(&out.MatchResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trap.
func (in *Trap) DeepCopy() *Trap {
	if in == nil {
		return nil
	}
	out := new(Trap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrapAnnotation) DeepCopyInto(out *TrapAnnotation) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.FilesystemHoneytoken = in.FilesystemHoneytoken
	out.HttpEndpoint = in.HttpEndpoint
	out.HttpPayload = in.HttpPayload
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrapAnnotation.
func (in *TrapAnnotation) DeepCopy() *TrapAnnotation {
	if in == nil {
		return nil
	}
	out := new(TrapAnnotation)
	in.DeepCopyInto(out)
	return out
}
